version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "21:12"
      timezone: Europe/Copenhagen
    labels: [dependencies, npm]
    commit-message:
      prefix: "🧱"
      include: scope

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "21:12"
      timezone: Europe/Copenhagen
    labels: [dependencies, docker]
    commit-message:
      prefix: "🧱"
      include: scope

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "21:12"
      timezone: Europe/Copenhagen
    labels: [dependencies, github-actions]
    commit-message:
      prefix: "🧱"
      include: scope
