{{- if .Values.infisical.enabled }}
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: {{ include "team-shuffler.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "team-shuffler.labels" . | nindent 4 }}
    environment: {{ .Values.environment | default "development" }}
spec:
  authentication:
    kubernetesAuth:
      autoCreateServiceAccountToken: true
      identityId: {{ .Values.infisical.identityId | quote }}
      secretsScope:
        envSlug: {{ .Values.infisical.envSlug | quote }}
        projectSlug: {{ .Values.infisical.projectSlug | quote }}
        secretsPath: {{ .Values.infisical.secretsPath | default "/" | quote }}
      serviceAccountRef:
        name: infisical-service-account
        namespace: {{ .Release.Namespace }}
  hostAPI: {{ .Values.infisical.hostAPI | quote }}
  managedKubeSecretReferences:
    - creationPolicy: Owner
      secretName: {{ include "team-shuffler.fullname" . }}-env
      secretNamespace: {{ .Release.Namespace }}
      secretType: Opaque
      template:
        includeAllSecrets: true
  resyncInterval: {{ .Values.infisical.resyncInterval | default 30 }}
{{- end }}
