{{- if .Values.infisical.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: infisical-service-account
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "team-shuffler.labels" . | nindent 4 }}
{{- end }}
